name: Swift Build

permissions:
  contents: read

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        strategy:
          fail-fast: false
          matrix:
           include:
            - os: macos-15
              xcode: "16.0"
            - os: macos-15
              xcode: "16.1"
            - os: macos-15
              xcode: "16.2"
            - os: macos-15
              xcode: "16.3"
            - os: macos-15
              xcode: "16.4"
            - os: macos-15
              xcode: "26.0.1"
            - os: macos-26
              xcode: "16.4"
            - os: macos-26
              xcode: "26.0.1"
        runs-on: ${{ matrix.os }}
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        steps:
            - uses: actions/checkout@v4

            - name: Restore .build
              id: restore-build
              uses: actions/cache/restore@v4
              with:
                path: .build
                restore-keys: "swiftpm-tests-build-${{ runner.os }}-${{ matrix.xcode }}-"
                key: "swiftpm-tests-build-${{ runner.os }}-${{ matrix.xcode }}-${{ github.event.pull_request.base.sha || github.event.after }}"

            - name: Build and Test
              run: set -o pipefail && swift test | xcbeautify --renderer github-actions

            - name: Cache .build
              if: steps.restore-build.outputs.cache-hit != 'true'
              uses: actions/cache/save@v4
              with:
                path: .build
                key: "swiftpm-tests-build-${{ runner.os }}-${{ matrix.xcode }}-${{ github.event.pull_request.base.sha || github.event.after }}"
